# Generated by Django 6.0 on 2025-12-29 18:46

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'interests',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('google_id', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('budget_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('provider_name', models.CharField(max_length=50)),
                ('provider_slug', models.CharField(db_index=True, max_length=50)),
                ('url', models.URLField(max_length=1000)),
                ('price', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=5, null=True)),
                ('rating', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=3, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('categories', models.JSONField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('source_hash', models.CharField(max_length=64, unique=True)),
                ('scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'courses',
                'indexes': [models.Index(fields=['provider_slug'], name='courses_provide_3e157d_idx'), models.Index(fields=['price'], name='courses_price_56bbb6_idx'), models.Index(fields=['rating'], name='courses_rating_757d69_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=5)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expenses',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user'], name='expenses_user_id_1a4067_idx'), models.Index(fields=['date'], name='expenses_date_a77b87_idx'), models.Index(fields=['category'], name='expenses_categor_a6f264_idx')],
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=500, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'refresh_tokens',
                'indexes': [models.Index(fields=['user'], name='refresh_tok_user_id_46676d_idx'), models.Index(fields=['expires_at'], name='refresh_tok_expires_a128d9_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInterest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to='api.interest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_interests',
                'indexes': [models.Index(fields=['user'], name='user_intere_user_id_61e710_idx'), models.Index(fields=['interest'], name='user_intere_interes_9d5382_idx')],
                'unique_together': {('user', 'interest')},
            },
        ),
        migrations.CreateModel(
            name='UserSavedCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_courses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_saved_courses',
                'indexes': [models.Index(fields=['user'], name='user_saved__user_id_9527ac_idx'), models.Index(fields=['course'], name='user_saved__course__faca98_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
    ]
