from django.core.management.base import BaseCommand
from api.models import Course
from decimal import Decimal
from datetime import datetime
import hashlib


class Command(BaseCommand):
    help = 'Seed the database with sample courses'

    def handle(self, *args, **kwargs):
        # Clear existing courses
        Course.objects.all().delete()
        self.stdout.write('Cleared existing courses')

        courses_data = [
            # Web Development Courses
            {
                'title': 'The Complete 2024 Web Development Bootcamp',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/the-complete-web-development-bootcamp/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '61 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/1565838_e54e_18.jpg',
                'description': 'Become a Full-Stack Web Developer with just ONE course.',
                'categories': ['Web Development', 'Programming', 'Full Stack'],
            },
            {
                'title': 'Modern JavaScript From The Beginning',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/modern-javascript-from-the-beginning/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '37 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/1463348_52a4_2.jpg',
                'description': 'Learn and build projects with pure JavaScript (No frameworks or libraries)',
                'categories': ['Web Development', 'Programming', 'JavaScript'],
            },
            {
                'title': 'React - The Complete Guide',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/react-the-complete-guide-incl-redux/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.6'),
                'duration': '49 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg',
                'description': 'Dive in and learn React.js from scratch!',
                'categories': ['Web Development', 'Programming', 'React'],
            },
            # Video Editing Courses
            {
                'title': 'Adobe Premiere Pro CC – Advanced Training Course',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/adobe-premiere-pro-video-editing/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.6'),
                'duration': '11 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1361498_7d11_2.jpg',
                'description': 'Master Adobe Premiere Pro CC for professional video editing',
                'categories': ['Video Editing', 'Adobe Premiere', 'Creative'],
            },
            {
                'title': 'Complete DaVinci Resolve 18 Video Editing Course',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/davinci-resolve-video-editing/',
                'price': Decimal('399'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '16 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/2451516_e8da.jpg',
                'description': 'Learn professional video editing with DaVinci Resolve',
                'categories': ['Video Editing', 'DaVinci Resolve', 'Creative'],
            },
            {
                'title': 'Video Editing Masterclass: Edit Your Videos Like a Pro!',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/video-editing-masterclass/',
                'price': Decimal('349'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '8 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1349346_9fa4_2.jpg',
                'description': 'Learn video editing fundamentals and advanced techniques',
                'categories': ['Video Editing', 'Creative', 'Filmmaking'],
            },
            # Data Science & Machine Learning
            {
                'title': 'Python for Data Science and Machine Learning Bootcamp',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.6'),
                'duration': '25 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/903744_8eb2.jpg',
                'description': 'Learn Python for Data Science, NumPy, Pandas, Matplotlib, Scikit-Learn, Machine Learning',
                'categories': ['Data Science', 'Machine Learning', 'Python', 'Programming'],
            },
            {
                'title': 'Machine Learning A-Z™: AI, Python & R',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/machinelearning/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '44 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/950390_270f_3.jpg',
                'description': 'Learn to create Machine Learning Algorithms in Python and R',
                'categories': ['Machine Learning', 'Data Science', 'AI', 'Python'],
            },
            # Digital Marketing
            {
                'title': 'The Complete Digital Marketing Course - 12 Courses in 1',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/learn-digital-marketing-course/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.4'),
                'duration': '23 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/1362070_b9a1_2.jpg',
                'description': 'Master Digital Marketing: SEO, Social Media, Email Marketing, and more!',
                'categories': ['Digital Marketing', 'SEO', 'Social Media', 'Business'],
            },
            {
                'title': 'SEO Training Masterclass 2024: Beginner to Advanced SEO',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/seo-training/',
                'price': Decimal('399'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '12 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1311626_6e96.jpg',
                'description': 'Learn SEO from scratch and rank #1 in Google',
                'categories': ['Digital Marketing', 'SEO', 'Marketing'],
            },
            # Graphic Design
            {
                'title': 'Graphic Design Masterclass - Learn GREAT Design',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/graphic-design-masterclass-everything-you-need-to-know/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.6'),
                'duration': '35 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1369830_ff90_4.jpg',
                'description': 'Learn all the main Graphic Design and Software Skills to become a Pro Graphic Designer',
                'categories': ['Graphic Design', 'Design', 'Creative', 'Adobe'],
            },
            {
                'title': 'Canva Master Course | Learn Canva For Graphic Design',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/canva-graphic-design-masterclass/',
                'price': Decimal('349'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '8 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/2452566_3ff7_2.jpg',
                'description': 'Master Canva and create stunning designs for social media, marketing, and more',
                'categories': ['Graphic Design', 'Design', 'Canva', 'Creative'],
            },
            # UI/UX Design
            {
                'title': 'User Experience Design Essentials - Adobe XD UI UX Design',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/ui-ux-web-design-using-adobe-xd/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '9 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1330926_1ce6.jpg',
                'description': 'Learn UI/UX Design with Adobe XD. User Interface, User Experience Design',
                'categories': ['UI/UX Design', 'Design', 'Adobe XD', 'User Experience'],
            },
            {
                'title': 'Complete Web & Mobile Designer: UI/UX, Figma, +more',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/complete-web-designer-mobile-designer-zero-to-mastery/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '24 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1472654_bfc0_3.jpg',
                'description': 'Become a Designer in 2024! Master Mobile and Web Design, UI/UX, Figma',
                'categories': ['UI/UX Design', 'Design', 'Figma', 'Web Design'],
            },
            # Photography
            {
                'title': 'Photography Masterclass: A Complete Guide to Photography',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/photography-masterclass-complete-guide-to-photography/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '23 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/358758_76e6_2.jpg',
                'description': 'Learn Digital Photography, Portrait, Product, Real Estate, Wedding Photography',
                'categories': ['Photography', 'Creative', 'Camera Skills'],
            },
            # Mobile App Development
            {
                'title': 'The Complete Android & Kotlin Development Masterclass',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/android-kotlin-developer/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '34 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/2443660_1994.jpg',
                'description': 'Learn Android App Development with Kotlin',
                'categories': ['Mobile App Development', 'Android', 'Kotlin', 'Programming'],
            },
            {
                'title': 'iOS & Swift - The Complete iOS App Development Bootcamp',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/ios-13-app-development-bootcamp/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.8'),
                'duration': '60 hours',
                'thumbnail_url': 'https://img-c.udemycdn.com/course/240x135/1778502_f4b9_12.jpg',
                'description': 'From Beginner to iOS App Developer with Just One Course',
                'categories': ['Mobile App Development', 'iOS', 'Swift', 'Programming'],
            },
            # Cybersecurity
            {
                'title': 'The Complete Cyber Security Course',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/the-complete-internet-security-privacy-course-volume-1/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '12 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1033458_81ce_3.jpg',
                'description': 'Learn Cybersecurity from scratch: Network Security, Ethical Hacking & more',
                'categories': ['Cybersecurity', 'IT', 'Security', 'Ethical Hacking'],
            },
            # Content Writing
            {
                'title': 'Content Writing: The Complete Guide to Writing Copy',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/content-writing-course/',
                'price': Decimal('349'),
                'currency': 'INR',
                'rating': Decimal('4.4'),
                'duration': '5 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1424816_d4c3.jpg',
                'description': 'Master content writing, copywriting, and creative writing',
                'categories': ['Content Writing', 'Writing', 'Copywriting', 'Marketing'],
            },
            # Game Development
            {
                'title': 'Complete C# Unity Game Developer 3D',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/unitycourse2/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '37 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/2466942_8de3.jpg',
                'description': 'Learn Unity 3D with C# and create your own games',
                'categories': ['Game Development', 'Unity', 'Programming', 'C#'],
            },
            # Cloud Computing
            {
                'title': 'AWS Certified Solutions Architect - Associate 2024',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/aws-certified-solutions-architect-associate-saa-c03/',
                'price': Decimal('499'),
                'currency': 'INR',
                'rating': Decimal('4.7'),
                'duration': '27 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/362070_b9a1_2.jpg',
                'description': 'Pass the AWS Certified Solutions Architect Associate Certification',
                'categories': ['Cloud Computing', 'AWS', 'IT', 'DevOps'],
            },
            # Business Analytics & Finance
            {
                'title': 'The Business Intelligence Analyst Course 2024',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/the-business-intelligence-analyst-course-2018/',
                'price': Decimal('449'),
                'currency': 'INR',
                'rating': Decimal('4.5'),
                'duration': '16 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/1445124_22e2.jpg',
                'description': 'Learn Business Intelligence, Data Analysis, and Data Visualization',
                'categories': ['Business Analytics', 'Data Analysis', 'Business', 'Finance & Accounting'],
            },
            {
                'title': 'Accounting & Bookkeeping Masterclass - Beginner to Advanced',
                'provider_name': 'Udemy',
                'provider_slug': 'udemy',
                'url': 'https://www.udemy.com/course/accounting-bookkeeping-masterclass/',
                'price': Decimal('399'),
                'currency': 'INR',
                'rating': Decimal('4.6'),
                'duration': '18 hours',
                'thumbnail_url': 'https://img-b.udemycdn.com/course/240x135/2404564_3bcb_2.jpg',
                'description': 'Learn accounting and bookkeeping from scratch',
                'categories': ['Finance & Accounting', 'Accounting', 'Business'],
            },
            # Coursera Courses
            {
                'title': 'Google Data Analytics Professional Certificate',
                'provider_name': 'Coursera',
                'provider_slug': 'coursera',
                'url': 'https://www.coursera.org/professional-certificates/google-data-analytics',
                'price': Decimal('3900'),
                'currency': 'INR',
                'rating': Decimal('4.8'),
                'duration': '6 months',
                'thumbnail_url': 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/fb/4e95e0b38211e8b9c3f3b9e24cd6/GCC_PGC_800x800.png',
                'description': 'Launch your career in Data Analytics',
                'categories': ['Data Science', 'Data Analysis', 'Google', 'Business Analytics'],
            },
            {
                'title': 'IBM Data Science Professional Certificate',
                'provider_name': 'Coursera',
                'provider_slug': 'coursera',
                'url': 'https://www.coursera.org/professional-certificates/ibm-data-science',
                'price': Decimal('3900'),
                'currency': 'INR',
                'rating': Decimal('4.6'),
                'duration': '11 months',
                'thumbnail_url': 'https://d3njjcbhbojbot.cloudfront.net/api/utilities/v1/imageproxy/https://coursera-course-photos.s3.amazonaws.com/c1/24b9f0d1a211e8b194f96ea1f4b54f/IBM-Data-Science-Logo.png',
                'description': 'Kickstart your career in data science & ML',
                'categories': ['Data Science', 'Machine Learning', 'IBM', 'Programming'],
            },
        ]

        # Create courses
        created_count = 0
        for course_data in courses_data:
            # Generate source hash from URL
            source_hash = hashlib.sha256(course_data['url'].encode()).hexdigest()
            
            course = Course.objects.create(
                title=course_data['title'],
                provider_name=course_data['provider_name'],
                provider_slug=course_data['provider_slug'],
                url=course_data['url'],
                price=course_data['price'],
                currency=course_data.get('currency', 'INR'),
                rating=course_data.get('rating'),
                duration=course_data.get('duration'),
                thumbnail_url=course_data.get('thumbnail_url'),
                description=course_data.get('description'),
                categories=course_data.get('categories', []),
                source_hash=source_hash,
                scraped_at=datetime.now()
            )
            created_count += 1

        self.stdout.write(
            self.style.SUCCESS(f'Successfully created {created_count} courses')
        )
